# Generated by Django 3.0.8 on 2020-07-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_order_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
